### ISSUE TITLE
Puppetboard link doesn't go to the specific report

### ISSUE THREAD

**Issue by rendhalver** [jamtur01/puppet-hipchat#38]
I am not actually sure if this is possible.
I noticed the puppetboard link goes to the latest report for the node in question.
It would be nice if it linked to the report that actually failed.

I will be having a dig through the code when I get a chance and see if I can make this work.

**Comment by james-powis** [comment]
@rendhalver having not used puppetboard or dashboard I would need to know if there was an extrapolated url to either which directly referenced the report id such as https://foo.com/report/#{report_id}/#{clientcert}

If so then it is highly likely this could be implemented fairly easily... I have had a goal of getting puppetboard up in my lab, but have not found the time yet...

**Comment by rendhalver** [comment]
I will run up a local instance and let you know.

**Comment by james-powis** [comment]
I got a local instance up and running at current latest and greatest, and despite my attempts I cannot get the code as is to return a report... http://dashboard/reports/latest/#{clientcert} returns a http error.

Additionally if the node is in an environment other than production oddities will be observed.

I was able to get this working though: http://dashboard/%2A/reports/#{clientcert} (%2A appears to mean all environments) which displays all reports for a specific node, and it is easy to scan through to find the failed run.

So I guess the question I have is did this ever work for puppetboard and then something changed?

**Comment by james-powis** [comment]
In the interest of completeness puppetboard uses what appears to be a UUID rather than a configuration version to piviot on in the url: http://puppetboard/%2A/report/testnode/d0eca540e23beb427d2ac6fea19a807856afda3b

Additionally the main reports screen does not allow for any externally defined / url encoded filter contexts to be applied... So the method above appears to be the best avenue.

**Comment by james-powis** [comment]
it appears the reports/latest was deprecated at version 1.0 if my interoperation of release notes is correct.

**Comment by james-powis** [comment]
OK more digging, i must have had a typo in the URL i was testing, report/latest/%{clientcert} does work. I am going to add a parameter to the config file to allow pointing to all reports for a node, this will allow for the consumer to drill into the failed report.

**Comment by href** [comment]
Actually, it turns out that Puppetboard supports a direct link to the configuration version in the latest release:
https://github.com/voxpupuli/puppetboard/blob/b7cd58ac2c1b1c1f1690e2e7e0c41eabc6e2c1e5/puppetboard/app.py#L591

So this would actually work (and does for the setup we run at work):

```ruby
if HIPCHAT_PUPPETBOARD
    msg << ": #{HIPCHAT_PUPPETBOARD}/report/#{self.host}/#{self.configuration_version}"
...
```

**Comment by james-powis** [comment]
@href Very Nice catch, i have an outstanding pullrequest which has not yet been accepted, I will get this implemented

**Comment by jamtur01** [comment]
@james-powis Would you like to maintain the module?

**Comment by james-powis** [comment]
@jamtur01 I would be more than happy to

**Comment by jamtur01** [comment]
Done! Thanks @james-powis - awesome stuff.

**Comment by james-powis** [comment]
OK so the functionality for * (%2A) was only added in the latest release of puppetboard v0.1.2: https://github.com/voxpupuli/puppetboard/commit/e93db585e16b5e316fb0645eda60dd01a360a96d#diff-0d8555c494fbab2daf14d6ce8e305355

Thus for backwards compatibility we cannot add that into the base URL structure... so I think documentation is in order to address that functionality / workaround. In short you can set the default environment to * in puppetboard or you can specify http://mypuppetboard/%2A as the hipchat::puppetboard url. I will get this into the docs

Also it looks like@href originally added the code in puppetboard 0.0.5 for accepting either hash or configuration_version, it has changed quite a bit since then but looks pretty well supported since that version. https://github.com/voxpupuli/puppetboard/commit/31a158c375b62947cb7d38cc4068bbf0935ec933

As such I think we can implement without impacting much compatibility.

**Comment by james-powis** [comment]
Changes have been merged. Closing

**Comment by href** [comment]
Cool, thank you!

> Also it looks like @href originally added the code in puppetboard 0.0.5 for accepting either hash or configuration_version, it has changed quite a bit since then but looks pretty well supported since that version. voxpupuli/puppetboard@31a158c

I totally forgot I did that 😀
